// Generated by gencpp from file whirlybird_msgs/MyStates.msg
// DO NOT EDIT!


#ifndef WHIRLYBIRD_MSGS_MESSAGE_MYSTATES_H
#define WHIRLYBIRD_MSGS_MESSAGE_MYSTATES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace whirlybird_msgs
{
template <class ContainerAllocator>
struct MyStates_
{
  typedef MyStates_<ContainerAllocator> Type;

  MyStates_()
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , roll_d(0.0)
    , pitch_d(0.0)
    , yaw_d(0.0)
    , Force(0.0)
    , Tau(0.0)  {
    }
  MyStates_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , roll_d(0.0)
    , pitch_d(0.0)
    , yaw_d(0.0)
    , Force(0.0)
    , Tau(0.0)  {
  (void)_alloc;
    }



   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _roll_d_type;
  _roll_d_type roll_d;

   typedef float _pitch_d_type;
  _pitch_d_type pitch_d;

   typedef float _yaw_d_type;
  _yaw_d_type yaw_d;

   typedef float _Force_type;
  _Force_type Force;

   typedef float _Tau_type;
  _Tau_type Tau;




  typedef boost::shared_ptr< ::whirlybird_msgs::MyStates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::whirlybird_msgs::MyStates_<ContainerAllocator> const> ConstPtr;

}; // struct MyStates_

typedef ::whirlybird_msgs::MyStates_<std::allocator<void> > MyStates;

typedef boost::shared_ptr< ::whirlybird_msgs::MyStates > MyStatesPtr;
typedef boost::shared_ptr< ::whirlybird_msgs::MyStates const> MyStatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::whirlybird_msgs::MyStates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::whirlybird_msgs::MyStates_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace whirlybird_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'whirlybird_msgs': ['/auto/fsc/rrhodes2/me431/new_whirly/whirlybird_ws/src/whirlybird_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::whirlybird_msgs::MyStates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whirlybird_msgs::MyStates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whirlybird_msgs::MyStates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whirlybird_msgs::MyStates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whirlybird_msgs::MyStates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whirlybird_msgs::MyStates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::whirlybird_msgs::MyStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f79d089f0886dd740744563939a637fd";
  }

  static const char* value(const ::whirlybird_msgs::MyStates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf79d089f0886dd74ULL;
  static const uint64_t static_value2 = 0x0744563939a637fdULL;
};

template<class ContainerAllocator>
struct DataType< ::whirlybird_msgs::MyStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "whirlybird_msgs/MyStates";
  }

  static const char* value(const ::whirlybird_msgs::MyStates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::whirlybird_msgs::MyStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Whirlybird.msg\n\
\n\
float32 roll\n\
float32 pitch\n\
float32 yaw\n\
\n\
float32 roll_d\n\
float32 pitch_d\n\
float32 yaw_d\n\
\n\
float32 Force\n\
float32 Tau\n\
";
  }

  static const char* value(const ::whirlybird_msgs::MyStates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::whirlybird_msgs::MyStates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.roll_d);
      stream.next(m.pitch_d);
      stream.next(m.yaw_d);
      stream.next(m.Force);
      stream.next(m.Tau);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MyStates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::whirlybird_msgs::MyStates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::whirlybird_msgs::MyStates_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "roll_d: ";
    Printer<float>::stream(s, indent + "  ", v.roll_d);
    s << indent << "pitch_d: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_d);
    s << indent << "yaw_d: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_d);
    s << indent << "Force: ";
    Printer<float>::stream(s, indent + "  ", v.Force);
    s << indent << "Tau: ";
    Printer<float>::stream(s, indent + "  ", v.Tau);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHIRLYBIRD_MSGS_MESSAGE_MYSTATES_H
