# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from whirlybird_msgs/MyStates.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MyStates(genpy.Message):
  _md5sum = "f79d089f0886dd740744563939a637fd"
  _type = "whirlybird_msgs/MyStates"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Whirlybird.msg

float32 roll
float32 pitch
float32 yaw

float32 roll_d
float32 pitch_d
float32 yaw_d

float32 Force
float32 Tau
"""
  __slots__ = ['roll','pitch','yaw','roll_d','pitch_d','yaw_d','Force','Tau']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       roll,pitch,yaw,roll_d,pitch_d,yaw_d,Force,Tau

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MyStates, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.roll is None:
        self.roll = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.roll_d is None:
        self.roll_d = 0.
      if self.pitch_d is None:
        self.pitch_d = 0.
      if self.yaw_d is None:
        self.yaw_d = 0.
      if self.Force is None:
        self.Force = 0.
      if self.Tau is None:
        self.Tau = 0.
    else:
      self.roll = 0.
      self.pitch = 0.
      self.yaw = 0.
      self.roll_d = 0.
      self.pitch_d = 0.
      self.yaw_d = 0.
      self.Force = 0.
      self.Tau = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_8f.pack(_x.roll, _x.pitch, _x.yaw, _x.roll_d, _x.pitch_d, _x.yaw_d, _x.Force, _x.Tau))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.roll, _x.pitch, _x.yaw, _x.roll_d, _x.pitch_d, _x.yaw_d, _x.Force, _x.Tau,) = _struct_8f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_8f.pack(_x.roll, _x.pitch, _x.yaw, _x.roll_d, _x.pitch_d, _x.yaw_d, _x.Force, _x.Tau))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.roll, _x.pitch, _x.yaw, _x.roll_d, _x.pitch_d, _x.yaw_d, _x.Force, _x.Tau,) = _struct_8f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_8f = struct.Struct("<8f")
